### ISSUE TITLE
CORS...

### ISSUE THREAD

**Issue by BigBlueHat** [BigBlueHat/userinfo#10]
[CORS](http://enable-cors.org/) is currently a blocker for XMLHttpRequest-based User-Info clients running in browsers.

For `http://byoung@bigbluehat.com/` (which works in `curl`...of course), I've setup the following CORS headers:
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
```

Not sure what else I'm missing...

**Comment by BigBlueHat** [comment]
@tilgovi you've successfully done the CORS, yeah? Any thoughts?

**Comment by tilgovi** [comment]
This is tricky. Since there's no specificity about what "credentials" means (type, etc) this is a bit of an issue.

I think my suggestion is to add `Access-Control-Allow-Headers: User-Info` or whatever your header is. Then, rely on browser clients to do the right thing. It won't work for clicking links / address bar to get the HTML representation, but it should work for JS clients. For other clients, like servers and CLI, there's no problem sending either and CORS is probably completely irrelevant anyway.

**Comment by BigBlueHat** [comment]
`Access-Control-Allow-Headers: User-Info` did it! Much thanks. :smile_cat:
